spring.application.name=leave_portal_app

# Server
server.port=${SERVER_PORT:8080}

# Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# OCI
oci.region=${OCI_REGION}
oci.namespace=${OCI_NAMESPACE}
oci.bucket-name=${OCI_BUCKET_NAME}
oci.object-prefix=${OCI_OBJECT_PREFIX}
oci.config-file=${OCI_CONFIG_FILE:${user.home}/.oci/config}
oci.profile=${OCI_PROFILE:DEFAULT}

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Oracle Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
gemini.api-key=${GEMINI_API_KEY}