spring.application.name=leave_portal_app

server.port=${SERVER_PORT:8080}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# OCI Object Storage
oci.region=${OCI_REGION:us-ashburn-1}
oci.namespace=${OCI_NAMESPACE:idqag2xakgns}
oci.bucket-name=${OCI_BUCKET_NAME:sick-leaves-bucket}
oci.config-file=${OCI_CONFIG_FILE:${user.home}/.oci/config}
oci.profile=${OCI_PROFILE:DEFAULT}

# Google OAuth 2.0
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# H2 Database
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/leave-portal-db}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console